export const FETCH_CHAT_TOKEN_PENDING = 'FETCH_CHAT_TOKEN_PENDING';
export const FETCH_CHAT_TOKEN_SUCCESS = 'FETCH_CHAT_TOKEN_SUCCESS';
export const FETCH_CHAT_TOKEN_ERROR = 'FETCH_CHAT_TOKEN_ERROR';
